# Web Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64  # Ensure the pod is scheduled on x86_64 (AMD64) nodes
      containers:
      - name: web
        image: origenai/cloud-engineer-test-sample-app-frontend:1.0.0
        ports:
        - containerPort: 3000
---
# API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64  # Ensure the pod is scheduled on x86_64 (AMD64) nodes
      containers:
      - name: api
        image: origenai/cloud-engineer-test-sample-app-backend:1.0.0
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URL
          value: "mongodb://mongo-service:27017"  # Update MongoDB connection to Kubernetes service name
---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64  # Ensure the pod is scheduled on x86_64 (AMD64) nodes
      containers:
      - name: mongo
        image: mongo
        env:
        - name: MONGODB_INITDB_ROOT_USERNAME
          value: "username"
        - name: MONGODB_INITDB_ROOT_PASSWORD
          value: "password"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongo-pvc
---
# Persistent Volume Claim for MongoDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Persistent Volume for MongoDB
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  # Ensure this path is valid on your node
