web:
  replicaCount: 1
  image:
    repository: origenai/cloud-engineer-test-sample-app-frontend
    tag: "1.0.0"
  service:
    type: LoadBalancer
    port: 3000

api:
  replicaCount: 1
  image:
    repository: origenai/cloud-engineer-test-sample-app-backend
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 3001

mongo:
  replicaCount: 1
  image:
    repository: mongo
  service:
    type: ClusterIP
    port: 27017
